<a href="https://colab.research.google.com/github/kursatkara/MAE_5020_S24/blob/master/03_40_Background.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import numpy as np

A = np.array([[2, 4, 6], [8, 10, 12]])

print("A matrix:")
print(A,"\n")

print("Flattened A matrix:")
print(A.flatten(),"\n")

print("mean of A, (flattened):",np.mean(A))
print("mean of A, axis = 0 (column):", np.mean(A,axis=0))
print("mean of A, axis = 1 (row):",np.mean(A,axis=1),"\n")


A matrix:
[[ 2  4  6]
 [ 8 10 12]] 

Flattened A matrix:
[ 2  4  6  8 10 12] 

mean of A, (flattened): 7.0
mean of A, axis = 0 (column): [5. 7. 9.]
mean of A, axis = 1 (row): [ 4. 10.] 



In [38]:
# np.random.randn, return a sample (or samples) from the “standard normal” distribution.
# It draw samples from a standard Normal distribution (mean=0, stdev=1).
A = np.random.randn(2,4)
print("Random A:\n", A)
print("Row mean of A:",np.mean(A, axis=1))
print("Standard deviation of A:",np.std(A))


Random A:
 [[ 0.71903053  0.90068206 -0.77244076 -0.92502995]
 [-0.34635461  1.04759899  0.90899525  0.4793898 ]]
Row mean of A: [-0.01943953  0.52240736]
Standard deviation of A: 0.7540007490826863


In [41]:
# Construct an array by repeating given number by repetitions

a = np.tile(1, 5)
print(a)

[1 1 1 1 1]


In [43]:
b = np.tile([1, 2], 5)
print(b)

[1 2 1 2 1 2 1 2 1 2]


In [44]:
c = np.tile([1, 2], (5,1))
print(c)

[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [1 2]]


In [47]:
c = np.tile([1, 2], (5,1)).T
print(c)

[[1 1 1 1 1]
 [2 2 2 2 2]]


In [48]:
d = np.tile([1, 2], (1,5))
print(d)

[[1 2 1 2 1 2 1 2 1 2]]
